### ISSUE TITLE
How the GB html works?

### ISSUE THREAD

**Issue by Pau1fitz** [notwaldorf/emoji-translate#10]
This really isn't an issue, but I thought by creating an issue would be the best way of finding this out.
How does < h1 >From 🇬🇧< /h1 > work in the HTML? When I look at the code it looks like the below screenshot.

I have seen this type of html recently, something similar is for this twitter page https://twitter.com/sindresorhus. Apologies in advance for raising this as an issue, but it's really bothering me that I can't figure out how this works/implement it myself.
🇬
<img width="191" alt="screen shot 2016-03-31 at 14 50 28" src="https://cloud.githubusercontent.com/assets/6873736/14177811/f3487e08-f74f-11e5-8c09-d11ae4cf0155.png">

**Comment by notwaldorf** [comment]
Oh, that's a great question! I don't know what your knowledge of emoji is, and the question is kind of general, so please don't take this as me trying to mansplain things -- i'm just going to tell you a whole bunch of things, and maybe some of them will be what you were looking for!

(just in case your question isn't about actual emoji: if no emoji are showing up on your page, it's because you need `<meta charset="utf-8">` in the head).

Now, about the flag emoji:
- every emoji is represented by a code point (a hexadecimal number, zero-padded up to at least four digits, like U+26C4). some emoji are boring (or in the "basic" unicode plane), which means one glyph is represented by one character. ☃ for example is U+2603 (you can find this out by doing `"☃".length` and `"☃".charCodeAt(0).toString(16)` in JavaScript)
- some emoji are more complicated (and live in "astral" planes), which means the code point has more than 4 digits. these are encoded by two 16-bit code units (this is called a "surrogate pair"). for example 🐼 is made up of two surrogates, U+D83D U+DC3C (`"🐼".charCodeAt(0).toString(16)` and `"🐼".charCodeAt(1).toString(16)`)
-  🇬🇧 and skin coloured emoji (and all the fancy modifier family ones) are "astral" plane emojis as well, only they're made out of 2 surrogate pairs, not 1 (so four 16-bit chars in total). The flags have a weird rule: each flag is made out of 2 pairs representing the country code, called regional indicators (which is why 🇬🇧 is `[G][B]`: the first surrogate pair represents the `[G]`, the second the `[B]`). Skin coloured emoji, for example, are made out of a normal emoji + one of 6 special characters representing the colour modifier.
- now that we figured out what unicode characters we need for  🇬🇧, we need to figure out how to render them. First, Chrome uses a text shaper (called [harfbuzz](https://www.freedesktop.org/wiki/Software/HarfBuzz/)) to convert the unicode character into a glyph (the thing you see on the screen). The text shaper is the one that knows how to look at these random characters, apply the modifiers correctly, and then figure out what glyph they represent. So for something like `GB`, it would make some magic happen and determine that this combination of regional indicators make the UK flag, so it would specify that's the glyph you need. Then, Harfbuzz passes this glyph information to Skia (which is the graphics library), and Skia draws the glyph on screen
- we also have to do a bit of work here to figure out how to use the fallback font. Basically Chrome tries to get this emoji glyph from the font you're using (for example, Helvetica). If it can't find it (which is likely, Helvetica doesn't have any emoji glyphs), it then uses the fallback font (on OSX this is `AppleColorEmoji`), and that's how it finds the right glyph. This is why you see the 🇬🇧 flag correctly
- in Atom, the reason why you see `[G][B]` instead, is that Atom is using an older version of Harfbuzz, so it doesn't know how to get the correct fallback font (this was only fixed in Chrome 50). So Harfbuzz has figured out the code points correspond to regional indicators, but doesn't know how to go ask `AppleColorEmoji` for them, so it's stuck using whatever glyphs your current font is providing, which are those letter squares. If you try something like a skin coloured thumbs up in Atom, you'll see the yellow thumbs up and the skin colour modifier (because in this case it knows to find the fallback font for each of the surrogate pairs, but not for the correct glyph as a whole):
<img width="73" alt="screen shot 2016-03-31 at 1 44 53 pm" src="https://cloud.githubusercontent.com/assets/1369170/14190286/c4475e70-f746-11e5-81dd-67eb5914ef79.png">

And that's how emoji works! Hope this helped!

**Comment by Pau1fitz** [comment]
wow! amazing answer, I literally knew none of this... now it's time to read and learn more about this, thank you, really appreciate it U+1F609
